version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.16.1
    steps:
      - checkout
      - run: npm install
      - run: npm run test:ci
      - store_test_results:
          path: test-results

